spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driverClassName=${DATABASE_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.jpa.database-platform=${DATABASE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.show-sql=false
spring.h2.console.enabled=false
logging.level.net.creft.lmm=INFO
