create table media_file (
    id bigint generated by default as identity primary key,
    media_id bigint not null,
    location varchar(2048) not null,
    file_order integer,
    constraint fk_media_file_media
        foreign key (media_id) references media(id) on delete cascade
);

create index idx_media_file_media_id on media_file (media_id);
